### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module 'webpack/lib/ParserHelpers'

### ISSUE THREAD

**Issue by ckken** [pmmmwh/react-refresh-webpack-plugin#126]
(node:50522) UnhandledPromiseRejectionWarning: Error: Cannot find module 'webpack/lib/ParserHelpers'
Require stack:
- /Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/index.js
- /Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/webpack/config/plugin.js
- /Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/webpack/config/common.js
- /Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/helpers/project.js
- /Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/scripts/dev.js
- /Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/bin/emp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/index.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
(node:50522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:50522) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pmmmwh** [comment]
Hi, can you please state the version of:

1. the plugin;
2. Webpack;


Providing me just the error stack trace is not helpful to say the least, because there is not much stuff for me to trace.

**Comment by ckken** [comment]
webpack: 5 beta 18
plugin version: 
"@pmmmwh/react-refresh-webpack-plugin": "^0.4.0-beta.5",
"react-refresh": "^0.8.3",

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/85936957-fdc05d80-b931-11ea-85cb-5a96251ec234.png)
update =>"@pmmmwh/react-refresh-webpack-plugin": "^0.4.0-beta.6"
use module federation

**Comment by pmmmwh** [comment]
Did you include the `webpack.HotModuleReplacementPlugin` in your Webpack configuration? If not, this plugin won't work.

With `webpack-dev-server` you can use either of the `hot`/`hotOnly` options, and with other development means you'll have to include it manually.

I've tested with module federation everything works fine.

**Comment by ckken** [comment]
> Did you include the `webpack.HotModuleReplacementPlugin` in your Webpack configuration? If not, this plugin won't work.
> 
> With `webpack-dev-server` you can use either of the `hot`/`hotOnly` options, and with other development means you'll have to include it manually.
> 
> I've tested with module federation (with Webpack master, cause there' some bugs with module cache in beta.18) and everything works fine.

nice

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/85984687-1a38c480-ba1c-11ea-991d-6e3cc0f53aaf.png)

**Comment by ckken** [comment]
no work for me！
```
devServer
module.exports = {
  devServer: {
    host: 'localhost',
    port: 8000,
    disableHostCheck: true,
    historyApiFallback: true,
    hot: true,
    stats: {
      colors: true,
    },
  },
}
// module
        scripts: {
          test: /\.(js|jsx|ts|tsx)$/,
          exclude: /node_modules/,
          use: {
            babel: {
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-env', '@babel/preset-typescript', '@babel/preset-react'],
                plugins: [
                  //
                  ['import', {libraryName: 'antd', style: true}],
                  isDev && require.resolve('react-refresh/babel'),
                  //
                ],
              },
            },
          },
        },
// plugin 
  if (isDev) {
    conf.plugin.reacthotloader = {
      plugin: ReactRefreshWebpackPlugin,
      args: [{}],
    }
  }


```

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/86000639-5ed65700-ba40-11ea-9aeb-2c0684979cc4.png)
when remove exposes it work!

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/86001050-ecb24200-ba40-11ea-8bf9-27150d7cf1d1.png)

**Comment by pmmmwh** [comment]
> ![image](https://user-images.githubusercontent.com/3890513/86000639-5ed65700-ba40-11ea-9aeb-2c0684979cc4.png)
> when remove exposes it work!

The issues you're facing is due to a bug in webpack@5.0.0-beta.18. if you use webpack master, these issues goes away. If they don't, or if you have any further questions, it is most likely not due to this plugin - we plug into Webpack's HMR runtime and if the HMR runtime errors out for module federation we can do nothing.

Side note: I would suggest adding `react-refresh/runtime` to shared singleton - you can also pin the version.

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/86080808-50cb1980-bac6-11ea-90ed-f22b32ae34bc.png)
no work also!

**Comment by ScriptedAlchemy** [comment]
go to beta 20

**Comment by ckken** [comment]
same issue

**Comment by ckken** [comment]
> go to beta 20

There are the same problems

**Comment by pmmmwh** [comment]
@ckken is it possible for you to share your full Webpack configuration files? It will be easier for us to figure out what is actually wrong - cause I've tested a few examples from the module federation org and stuff works ...

@ScriptedAlchemy it seems that on refresh HMR breaks too, I'll provide a simple repro.

**Comment by ckken** [comment]
webpack config:   
```js
 {
  mode: 'development',
  devtool: 'inline-source-map',
  output: {
    path: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/demo1/dist',
    filename: 'js/[name].[contenthash:8].js',
    publicPath: 'http://localhost:8001/'
  },
  resolve: {
    alias: {
      src: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/demo1/src'
    },
    extensions: [
      '.js',
      '.jsx',
      '.ts',
      '.tsx',
      '.css',
      '.less',
      '.scss',
      '.sass',
      '.json'
    ],
    modules: [
      'node_modules',
      '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/demo1/node_modules',
      '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/demo1/src'
    ]
  },
  devServer: {
    host: 'localhost',
    port: 8001,
    disableHostCheck: true,
    historyApiFallback: true,
    open: false,
    hot: false,
    stats: {
      colors: true
    }
  },
  module: {
    rules: [
      /* config.module.rule('css') */
      {
        test: /\.css$/,
        exclude: [
          /\.module\.css$/
        ],
        use: [
          /* config.module.rule('css').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('css').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js'
          }
        ]
      },
      /* config.module.rule('cssModule') */
      {
        test: /\.module\.css$/,
        exclude: [
          /\.css$/
        ],
        use: [
          /* config.module.rule('cssModule').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('cssModule').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js',
            options: {
              modules: true
            }
          }
        ]
      },
      /* config.module.rule('sassModule') */
      {
        test: /\.module\.(scss|sass)$/,
        exclude: [
          /\.(scss|sass)$/
        ],
        use: [
          /* config.module.rule('sassModule').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('sassModule').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js',
            options: {
              modules: true
            }
          },
          /* config.module.rule('sassModule').use('sass') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/sass-loader/dist/cjs.js',
            options: {
              implementation: {
                render: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                },
                renderSync: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                },
                info: 'dart-sass\t1.26.7\t(Sass Compiler)\t[Dart]\ndart2js\t2.8.2\t(Dart Compiler)\t[Dart]',
                types: {
                  Boolean: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  },
                  Color: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  List: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Map: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Null: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  },
                  Number: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  String: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Error: function Error() { [native code] }
                },
                NULL: {
                  toString: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  }
                },
                TRUE: {
                  value: true
                },
                FALSE: {
                  value: false
                },
                cli_pkg_main_0_: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                }
              },
              sourceMap: true
            }
          }
        ]
      },
      /* config.module.rule('sass') */
      {
        test: /\.(scss|sass)$/,
        exclude: [
          /\.module\.(scss|sass)$/
        ],
        use: [
          /* config.module.rule('sass').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('sass').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js'
          },
          /* config.module.rule('sass').use('sass') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/sass-loader/dist/cjs.js',
            options: {
              implementation: {
                render: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                },
                renderSync: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                },
                info: 'dart-sass\t1.26.7\t(Sass Compiler)\t[Dart]\ndart2js\t2.8.2\t(Dart Compiler)\t[Dart]',
                types: {
                  Boolean: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  },
                  Color: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  List: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Map: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Null: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  },
                  Number: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  String: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Error: function Error() { [native code] }
                },
                NULL: {
                  toString: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  }
                },
                TRUE: {
                  value: true
                },
                FALSE: {
                  value: false
                },
                cli_pkg_main_0_: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                }
              },
              sourceMap: true
            }
          }
        ]
      },
      /* config.module.rule('less') */
      {
        test: /\.less$/,
        exclude: [
          /\.module\.less$/
        ],
        use: [
          /* config.module.rule('less').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('less').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js'
          },
          /* config.module.rule('less').use('sass') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/less-loader/dist/cjs.js',
            options: {
              lessOptions: {
                javascriptEnabled: true
              }
            }
          }
        ]
      },
      /* config.module.rule('lessModule') */
      {
        test: /\.module\.less$/,
        exclude: [
          /\.less$/
        ],
        use: [
          /* config.module.rule('lessModule').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('lessModule').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js',
            options: {
              modules: true
            }
          },
          /* config.module.rule('lessModule').use('sass') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/less-loader/dist/cjs.js',
            options: {
              lessOptions: {
                javascriptEnabled: true
              }
            }
          }
        ]
      },
      /* config.module.rule('image') */
      {
        test: /\.(png|jpe?g|gif|svg)$/i,
        use: [
          /* config.module.rule('image').use('file') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/file-loader/dist/cjs.js'
          }
        ]
      },
      /* config.module.rule('scripts') */
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: [
          /node_modules/
        ],
        use: [
          /* config.module.rule('scripts').use('babel') */
          {
            loader: 'babel-loader',
            options: {
              presets: [
                '@babel/preset-env',
                '@babel/preset-typescript',
                '@babel/preset-react'
              ],
              plugins: [
                [
                  'import',
                  {
                    libraryName: 'antd',
                    style: true
                  }
                ]
              ]
            }
          }
        ]
      }
    ]
  },
  optimization: {
    chunkIds: 'named',
    usedExports: true
  },
  plugins: [
    /* config.plugin('env') */
    new EnvironmentPlugin(
      {
        MODE_ENV: 'development',
        EMP_ENV: 'dev'
      }
    ),
    /* config.plugin('clean') */
    new CleanWebpackPlugin(ndefine),
    /* config.plugin('html') */
    new HtmlWebpackPlugin(
      {
        title: 'EMP',
        template: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/template/public/index.html',
        favicon: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/template/public/favicon.ico',
        files: {
          js: [
            'http://localhost:8002/emp.js'
          ]
        },
        minify: false
      }
    ),
    /* config.plugin('progress') */
    new ProgressPlugin(
      {
        handler: function () { /* omitted long function */ }
      }
    ),
    /* config.plugin('mf') */
    new ModuleFederationPlugin(
      {
        name: 'demo1',
        library: {
          type: 'var',
          name: 'demo1'
        },
        filename: 'emp.js',
        remotes: {
          '@emp/demo2': 'demo2'
        },
        exposes: {
          './components/Demo': 'src/components/Demo',
          './components/Hello': 'src/components/Hello'
        },
        shared: [
          'react',
          'react-dom'
        ]
      }
    ),
    /* config.plugin('ts') */
    new ForkTsCheckerWebpackPlugin(
      {
        tsconfig: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/demo1/tsconfig.json'
      }
    )
  ],
  entry: {
    index: [
      '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/demo1/src/index.ts'
    ]
  }
}
```

**Comment by ckken** [comment]
webpack config for development 
```js
{
  mode: 'development',
  devtool: 'inline-source-map',
  output: {
    path: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/antd-base/dist',
    filename: 'js/[name].[contenthash:8].js',
    publicPath: 'http://localhost:8003/'
  },
  resolve: {
    alias: {
      src: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/antd-base/src'
    },
    extensions: [
      '.js',
      '.jsx',
      '.ts',
      '.tsx',
      '.css',
      '.less',
      '.scss',
      '.sass',
      '.json'
    ],
    modules: [
      'node_modules',
      '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/antd-base/node_modules',
      '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/antd-base/src'
    ]
  },
  devServer: {
    host: 'localhost',
    port: 8003,
    disableHostCheck: true,
    historyApiFallback: true,
    open: false,
    hot: true,
    stats: {
      colors: true
    }
  },
  module: {
    rules: [
      /* config.module.rule('css') */
      {
        test: /\.css$/,
        exclude: [
          /\.module\.css$/
        ],
        use: [
          /* config.module.rule('css').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('css').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js'
          }
        ]
      },
      /* config.module.rule('cssModule') */
      {
        test: /\.module\.css$/,
        exclude: [
          /\.css$/
        ],
        use: [
          /* config.module.rule('cssModule').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('cssModule').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js',
            options: {
              modules: true
            }
          }
        ]
      },
      /* config.module.rule('sassModule') */
      {
        test: /\.module\.(scss|sass)$/,
        exclude: [
          /\.(scss|sass)$/
        ],
        use: [
          /* config.module.rule('sassModule').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('sassModule').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js',
            options: {
              modules: true
            }
          },
          /* config.module.rule('sassModule').use('sass') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/sass-loader/dist/cjs.js',
            options: {
              implementation: {
                render: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                },
                renderSync: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                },
                info: 'dart-sass\t1.26.7\t(Sass Compiler)\t[Dart]\ndart2js\t2.8.2\t(Dart Compiler)\t[Dart]',
                types: {
                  Boolean: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  },
                  Color: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  List: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Map: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Null: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  },
                  Number: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  String: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Error: function Error() { [native code] }
                },
                NULL: {
                  toString: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  }
                },
                TRUE: {
                  value: true
                },
                FALSE: {
                  value: false
                },
                cli_pkg_main_0_: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                }
              },
              sourceMap: true
            }
          }
        ]
      },
      /* config.module.rule('sass') */
      {
        test: /\.(scss|sass)$/,
        exclude: [
          /\.module\.(scss|sass)$/
        ],
        use: [
          /* config.module.rule('sass').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('sass').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js'
          },
          /* config.module.rule('sass').use('sass') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/sass-loader/dist/cjs.js',
            options: {
              implementation: {
                render: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                },
                renderSync: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                },
                info: 'dart-sass\t1.26.7\t(Sass Compiler)\t[Dart]\ndart2js\t2.8.2\t(Dart Compiler)\t[Dart]',
                types: {
                  Boolean: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  },
                  Color: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  List: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Map: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Null: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  },
                  Number: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  String: function () {
                    return _call(f, this, Array.prototype.slice.apply(arguments));
                  },
                  Error: function Error() { [native code] }
                },
                NULL: {
                  toString: function () {
                    return _call(f, Array.prototype.slice.apply(arguments));
                  }
                },
                TRUE: {
                  value: true
                },
                FALSE: {
                  value: false
                },
                cli_pkg_main_0_: function () {
                  return _call(f, Array.prototype.slice.apply(arguments));
                }
              },
              sourceMap: true
            }
          }
        ]
      },
      /* config.module.rule('less') */
      {
        test: /\.less$/,
        exclude: [
          /\.module\.less$/
        ],
        use: [
          /* config.module.rule('less').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('less').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js'
          },
          /* config.module.rule('less').use('sass') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/less-loader/dist/cjs.js',
            options: {
              lessOptions: {
                javascriptEnabled: true
              }
            }
          }
        ]
      },
      /* config.module.rule('lessModule') */
      {
        test: /\.module\.less$/,
        exclude: [
          /\.less$/
        ],
        use: [
          /* config.module.rule('lessModule').use('style') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/style-loader/dist/cjs.js'
          },
          /* config.module.rule('lessModule').use('css') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/css-loader/dist/cjs.js',
            options: {
              modules: true
            }
          },
          /* config.module.rule('lessModule').use('sass') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/less-loader/dist/cjs.js',
            options: {
              lessOptions: {
                javascriptEnabled: true
              }
            }
          }
        ]
      },
      /* config.module.rule('image') */
      {
        test: /\.(png|jpe?g|gif|svg)$/i,
        use: [
          /* config.module.rule('image').use('file') */
          {
            loader: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/file-loader/dist/cjs.js'
          }
        ]
      },
      /* config.module.rule('scripts') */
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: [
          /node_modules/
        ],
        use: [
          /* config.module.rule('scripts').use('babel') */
          {
            loader: 'babel-loader',
            options: {
              presets: [
                '@babel/preset-env',
                '@babel/preset-typescript',
                '@babel/preset-react'
              ],
              plugins: [
                [
                  'import',
                  {
                    libraryName: 'antd',
                    style: true
                  }
                ],
                '/Users/ken/Desktop/develop/MicroFE/emp-workspace/node_modules/react-refresh/babel.js'
              ]
            }
          }
        ]
      }
    ]
  },
  optimization: {
    chunkIds: 'named',
    usedExports: true
  },
  plugins: [
    /* config.plugin('env') */
    new EnvironmentPlugin(
      {
        MODE_ENV: 'development',
        EMP_ENV: 'dev'
      }
    ),
    /* config.plugin('clean') */
    new CleanWebpackPlugin(ndefine),
    /* config.plugin('html') */
    new HtmlWebpackPlugin(
      {
        title: 'EMP BASE',
        template: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/template/public/index.html',
        favicon: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/packages/emp-cli/template/public/favicon.ico',
        files: {},
        minify: false
      }
    ),
    /* config.plugin('progress') */
    new ProgressPlugin(
      {
        handler: function () { /* omitted long function */ }
      }
    ),
    /* config.plugin('mf') */
    new ModuleFederationPlugin(
      {
        name: 'empBase',
        library: {
          type: 'var',
          name: 'empBase'
        },
        filename: 'emp.js',
        remotes: {},
        exposes: {
          './App': 'src/App',
          './stores/index': 'src/stores/index',
          './components/common/crud/index': 'src/components/common/crud/index',
          './components/common/RouterComp': 'src/components/common/RouterComp'
        },
        shared: {
          react: {
            eager: true,
            singleton: true,
            requiredVersion: '^16.13.1'
          },
          'react-dom': {
            eager: true,
            singleton: true,
            requiredVersion: '^16.13.1'
          },
          'react-router-dom': {
            requiredVersion: '^5.1.2'
          },
          'mobx-react-lite': {
            requiredVersion: '^1.5.2'
          },
          mobx: {
            requiredVersion: '^5.15.4'
          },
          axios: {
            requiredVersion: '^0.19.2'
          }
        }
      }
    ),
    /* config.plugin('ts') */
    new ForkTsCheckerWebpackPlugin(
      {
        tsconfig: '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/antd-base/tsconfig.json'
      }
    ),
    /* config.plugin('reacthotloader') */
    new ReactRefreshPlugin(
      {}
    )
  ],
  entry: {
    index: [
      '/Users/ken/Desktop/develop/MicroFE/emp-workspace/projects/antd-base/src/index.ts'
    ]
  }
}
```

**Comment by ckken** [comment]
revert to webpack5-beta-16 every thing goes well

**Comment by ckken** [comment]
```json
 "@pmmmwh/react-refresh-webpack-plugin": "https://github.com/pmmmwh/react-refresh-webpack-plugin#main",
```
it no work for me 
https://github.com/module-federation/module-federation-examples/issues/138#issuecomment-654614565

**Comment by pmmmwh** [comment]
I won't have time to test module federation this week most likely, but from what I see in the screenshot it is some sort of error within Webpack's JSONP HMR runtime - which is way out of scope of this plugin.

@ckken I would suggest you redirect your troubleshooting to webpack/webpack#10352 (I will join the discussion if I see anything related), with a minimal reproducible example (like how I did upstairs, strip away all unrelated stuff e.g. CSS and focus on MF) so that Tobias/Zack can have a failing baseline to build on (think of TDD - the example acts as a test where we implement code to make it pass). While screenshots shows traces of where the error originates without the whole picture it is difficult for anyone to track down issues, especially when it is tech like this that orchestrates stuff.

**Comment by flyyuan** [comment]
mark

**Comment by pmmmwh** [comment]
From #195, reported by @shaodahong

> Report: [shaodahong/module-federation-react-refresh-demo](https://github.com/shaodahong/module-federation-react-refresh-demo)
> 
> if change some text trigger refresh, console log some error
> 
> @pmmmwh @ScriptedAlchemy
> 
> ![image](https://user-images.githubusercontent.com/14831261/91957723-002ba300-ed39-11ea-9770-43a9ccec5c65.png)

**Comment by shaodahong** [comment]
Relate https://github.com/webpack/webpack-dev-server/issues/2692

**Comment by shaodahong** [comment]
Now `webpack-dev-server` release [beta](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0), it's resolved multiple entrypoint hot refresh, and if still has an error, can report to `webpack-dev-server`

**Comment by ckken** [comment]
TypeError: WebpackDevServer.addDevServerEntrypoints is not a function

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/100505414-bc193480-31a7-11eb-9b12-8b9bef10e6f1.png)

**Comment by ckken** [comment]
![Uploading image.png…]()

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/100507007-3649b900-31a8-11eb-83fb-cd556c67fb05.png)

**Comment by ckken** [comment]
+ `git clone https://github.com/efoxTeam/emp`
+ `lerna bootstrap`
+ `cd projects && yarn dev:hot`
+ change `https://github.com/efoxTeam/emp/blob/main/projects/demo1/src/bootstrap.tsx` & throw error

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/100566819-f696e480-3301-11eb-93d8-698b9dfe69a0.png)
fixed it

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/100568031-f2b89180-3304-11eb-844d-aadf35623383.png)
Fixed cross domain issues, but page changed from hot to refresh

**Comment by ckken** [comment]
TypeError: Cannot read property 'requestContent' of undefined

**Comment by ckken** [comment]
![Uploading image.png…]()

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/100573696-5cd83300-3313-11eb-9cfa-89931f21819a.png)

**Comment by ckken** [comment]
I found that there would be problems when project a was import into project B

**Comment by shaodahong** [comment]
like `hot replace` and `liveReload` both active, `liveReload` it's fallback

**Comment by ckken** [comment]
`liveReload` is disabled
![image](https://user-images.githubusercontent.com/3890513/100583184-505cd600-3325-11eb-8d42-c3ddf35a76e9.png)
I found possible problems

**Comment by akphi** [comment]
@pmmmwh not sure if this is related, but as @shaodahong mentioned [webpack-dev-server@4.0.0-beta.0](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0). I found that `fast-refresh` no-longer works.

I have a reproducible repo, please take a look at this [PR](https://github.com/akphi/config-tester/pull/12). After upgrading to `webpack-dev-server@4.0.0-beta.0`. If you run the app using `yarn start` and try to hit the `+` button a few time to increase the age, then you try to make some trivial change in `App.tsx` the page is reloaded, and the age is reset to `10`.

**Comment by shaodahong** [comment]
> @pmmmwh not sure if this is related, but as @shaodahong mentioned `webpack-dev-server` just released [v4.0.0-beta.0](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0); and as I just tried it out, I found that `fast-refresh` no-longer works.
> 
> I have a reproducible repo, please take a look at this [PR](https://github.com/akphi/config-tester/pull/12). After upgrading to `webpack-dev-server@4.0.0-beta.0`. If you run the app using `yarn start` and try to hit the `+` button a few time to increase the age, then you try to make some trivial change in `App.tsx` the page is reloaded, and the age is reset to `10`.
> 
> @pmmmwh if you would like me to file a separate issue, please let me know.

@akphi can you set `webpack-dev-server` `liveReload: false`?

**Comment by akphi** [comment]
@shaodahong Yes, that seems to work just fine. Thank you! @pmmmwh should we just consider this as a workaround for now?

**Comment by akphi** [comment]
looks like rather a matter of disabling `liveReload` explicitly, it could be due to some change to the default value set for `watchContentBase` in their `v4.beta`, I did a bit of digging and filed an issue with `webpack-dev-server` https://github.com/webpack/webpack-dev-server/issues/2893

**Comment by shaodahong** [comment]
@akphi yep, but this PR talk about use `ModuleFederationPlugin`, crash when multiple entrypoint

**Comment by ckken** [comment]
it work for esbuild https://github.com/efoxTeam/emp/tree/main/projects/esbuild-react-demo

**Comment by ckken** [comment]
it work for swc https://github.com/efoxTeam/emp/tree/main/projects/swc-react-demo too

**Comment by pmmmwh** [comment]
I'm not sure what we're looking for here now - it seems to me most of the errors tracked within this thread is not our issue but rather from upstream (`webpack-dev-server`)? I'm not sure what you mean by working for `esbuild` or `swc` to be honest.

**Comment by pmmmwh** [comment]
#394
