### ISSUE TITLE
Cannot read property 'forEach' of undefined -- Only on macOS

### ISSUE THREAD

**Issue by Slapbox** [pmmmwh/react-refresh-webpack-plugin#333]
**Error message:**

```
19:16:33.302 › TypeError: Cannot read property 'forEach' of undefined
    at Object.injectIntoGlobalHook (webpack-internal:///./node_modules/react-refresh/cjs/react-refresh-runtime.development.js:461:20)
    at eval (webpack-internal:///./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js:8:20)
    at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js (http://localhost:1212/dist/renderer.dev.js:1448:1)
    at Object.options.factory (http://localhost:1212/dist/renderer.dev.js:26372:31)
    at __webpack_require__ (http://localhost:1212/dist/renderer.dev.js:25711:33)
    at http://localhost:1212/dist/renderer.dev.js:26927:11
    at http://localhost:1212/dist/renderer.dev.js:26935:12
setTimeout (async)
consoleLog @ console.js:93
transport @ console.js:46
runTransport @ log.js:44
(anonymous) @ ipc.js:21
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:91
```

Identical setup works perfectly on Windows and Linux so I'm not really sure what to make of it. I tried deleting the entire `node_modules` folder and reinstalling, but the issue persists.

**Environment:**
- macOS 10.13.x
- Electron 11.3.x

**Comment by Slapbox** [comment]
`yarn cache clean` and then rebuilding `node_modules` fresh also didn't work.

Perhaps related to #319?

**Comment by pmmmwh** [comment]
The issue seems to originate from the `react-refresh/runtime` instead of this plugin.
Mind filing an issue on the React repo instead?

Are you sure your runtime have a working `Map` or `Set` implementation?

**Comment by Slapbox** [comment]
Ah good catch. Yeah we definitely have `Map` and `Set` support in our environment. I'll post the issue over there.

**Comment by pmmmwh** [comment]
Closed: https://github.com/facebook/react/issues/21047

**Comment by Slapbox** [comment]
Whoops my bad, I thought the issue was already closed on this end. That's some damn speedy maintenance @pmmmwh!
