### ISSUE TITLE
Error when trying to expose a module with Module Federation

### ISSUE THREAD

**Issue by mlshv** [pmmmwh/react-refresh-webpack-plugin#429]
Hi! I'm trying to make the plugin work with WP5 Module Federation but I get the following error:

```
｢wdm｣: TypeError: Cannot read property 'includes' of undefined
    at /Users/mmmm/code/mfe-material/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:105:27
    at Array.findIndex (<anonymous>)
    at /Users/mmmm/code/mfe-material/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:104:50
    at Hook.eval [as callAsync] (eval at create (/Users/mmmm/code/mfe-material/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:97:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mmmm/code/mfe-material/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/mmmm/code/mfe-material/node_modules/webpack/lib/Compiler.js:1081:20
    at Hook.eval [as callAsync] (eval at create (/Users/mmmm/code/mfe-material/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mmmm/code/mfe-material/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/mmmm/code/mfe-material/node_modules/webpack/lib/Compiler.js:1071:28)
    at /Users/mmmm/code/mfe-material/node_modules/webpack/lib/Watching.js:188:19
```

I've created a repo with reproduction: https://github.com/mlshv/mfe-react-refresh-bug

The error goes away when I comment exposed module:

```js
// webpack.config.js

plugins: [
    new ModuleFederationPlugin({
        name: '_main',
        filename: 'remoteEntry.js',
        exposes: {
            './App': './src/App.js', // comment this line to make the error go away
        },
    }),
    new HtmlWebpackPlugin({
        template: 'src/index.html',
    }),
    new ReactRefreshWebpackPlugin(),
],
```

**Comment by nctay** [comment]
Same error.
@pmmmwh, is there anything you can do?
