### ISSUE TITLE
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by kocendavid** [pmmmwh/react-refresh-webpack-plugin#639]
Hi sorry if solved or irrelevant question. I get this error when I try to import React component into util function in .js file that is not react component.

import in file notification.js
```
import { Alert } from '@ui' // (also tried '../componets/ui')

const error = () => {
  toast.custom(() => (
      <Alert
        type={Alert.TYPES.ERROR}
        text={t(message)}
      />
    ),
    {
      duration: 5000,
      position: 'top-right'
    })
}
```
```
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Object.default (error.js:2:42)
    at Object.errorUtil (index.js:7:99)
    at registerExportsForReactRefresh (RefreshUtils.jss?f780:158:1)
    at Object.executeRuntime (RefreshUtils.jss?f780:193:1)
    at $ReactRefreshModuleRuntime$ (index.jss?0e7a:19:1)
    at eval (index.jss?0e7a:19:1)
    at Object../app/util/index.js (main.cbb1788d12ff8508e4b7.js:9511:1)
    at Object.options.factory (main.cbb1788d12ff8508e4b7.js:13210:31)
    at __webpack_require__ (main.cbb1788d12ff8508e4b7.js:12592:33)
    at fn (main.cbb1788d12ff8508e4b7.js:12881:21)
   ```
    versions
    "webpack": "5.69.1"
    "react": "18.0.0",
    "@pmmmwh/react-refresh-webpack-plugin": "0.5.6",
    node: 17.6.0
    
    Code works if I remove fast refresh from webpack or Alert import from notification.js file

**Comment by pmmmwh** [comment]
Hi, can you create a reproducible example for investigation?

**Comment by kocendavid** [comment]
Works now. Guess it wasnt problem of the library. Tanks for your time
