### ISSUE TITLE
Error: Unknown keyword formatMinimum

### ISSUE THREAD

**Issue by nathanredblur** [pmmmwh/react-refresh-webpack-plugin#676]
I'm so lost, this module works in my computer but not in my docker instance created in CI env.
this problem appears after migrate this module from "^0.4.3" to "^0.5.7"

```
[webpack-cli] Error: Unknown keyword formatMinimum
    at get (/workdir/node_modules/ajv-keywords/dist/index.js:25:15)
    at ajvKeywords (/workdir/node_modules/ajv-keywords/dist/index.js:10:13)
    at Object.<anonymous> (/workdir/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/schema-utils/dist/validate.js:58:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/workdir/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/schema-utils/dist/index.js:3:18)
```

I have a monorepo and this error on run my build but only in CI. any idea?

**Comment by pmmmwh** [comment]
Hi, it is likely that you have two versions of `schema-utils` installed inside your monorepo setup - it should work once you resolve that (or ensure this plugin gets the correct version)
