### ISSUE TITLE
overlay.sockIntegration does not receive 'wds' default

### ISSUE THREAD

**Issue by billyjanitsch** [pmmmwh/react-refresh-webpack-plugin#68]
The `0.3.0-beta.2` docs say that `options.overlay.sockIntegration` [defaults to `'wds'`](https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/e93e3765fb83fababc7f52858b196ae3229e0676#optionsoverlaysockintegration), but I don't see any part of the codebase responsible for providing that default.

As a result, running the [webpack-dev-server example](https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/e93e3765fb83fababc7f52858b196ae3229e0676/examples/webpack-dev-server) in the repo throws the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Function.resolve (internal/modules/cjs/helpers.js:77:5)
    at getSocketIntegration (/[...]/react-refresh-webpack-plugin/examples/webpack-dev-server/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/helpers/getSocketIntegration.js:11:43)
    at ReactRefreshPlugin.apply (/[...]/react-refresh-webpack-plugin/examples/webpack-dev-server/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/index.js:47:23)
```

This is because `options.overlay.sockIntegration` is `undefined` and eventually gets passed as an argument to `require.resolve`.

**Comment by pmmmwh** [comment]
Thanks for reporting, I deleted the line accidentally. A fix is on its way.
