### ISSUE TITLE
Plugin seems to not like working in SSR

### ISSUE THREAD

**Issue by mvittiglio** [pmmmwh/react-refresh-webpack-plugin#703]
While the page refreshes automatically as expected, if I am in need of refreshing the page (or opening a new page even) the page will error out complaining of even the smallest change (just text, for example). 

`Warning: Text content did not match. Server: "Hello, dude! Click count: " Client: "Hello, fella! Click count: "
    at h1
    at div
    at HelloWorld (http://localhost:3000/dist/bundle.js:3996:66)
    at Router (http://localhost:3000/dist/bundle.js:42092:15)
    at BrowserRouter (http://localhost:3000/dist/bundle.js:40322:5)
    at App
node_modules/react-dom/cjs/react-dom.development.js:86
Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>.`

Is this plugin incompatible with SSR methodologies?

**Comment by childrentime** [comment]
any fix? same issue

**Comment by Kallenju** [comment]
Everything works. I added the plugin to the Webpack for both the client and the server config to make it work.

**Comment by childrentime** [comment]
@Kallenju can you give a simple repo example?

**Comment by Kallenju** [comment]
> @Kallenju can you give a simple repo example?

Of course. But, I want to warn you that now I am noob in React

https://github.com/Kallenju/template-for-react-ts-ssr-hmr

For start:

```shell
npm install

npm run dev
```

**Comment by childrentime** [comment]
thanks! It seems to work well. I think my mistake was caused by I do not restart nodejs server.

**Comment by adbutterfield** [comment]
I have a template repo as well with SSR: https://github.com/adbutterfield/fast-refresh-express
