### ISSUE TITLE
Server side rendering : $RefreshReg$ is not defined

### ISSUE THREAD

**Issue by tomtom94** [pmmmwh/react-refresh-webpack-plugin#739]
Hello,

I have an SSR config, which doesn't like `react-refresh/babel` on the server side.

I made a repository branch `react-refresh-issue` to reproduce the issue 
https://github.com/tomtom94/react-easy-ssr/tree/react-refresh-issue

Find the `babel.config.js`link below
https://github.com/tomtom94/react-easy-ssr/blob/react-refresh-issue/babel.config.js#L30-L32

```
$ npm run dev

> react-easy-ssr@v8.1.1 dev
> node scripts/dev.js

Compiling client please wait...
Compiling server please wait...
8 assets
108 modules
webpack 5.74.0 compiled successfully in 4556 ms
27 assets
461 modules
webpack 5.74.0 compiled successfully in 5992 ms
Hot dev server middleware port : 3001 🌎
webpack://react-easy-ssr/./src/assets/jss/components/cssBaselineStyle.ts?:335
$RefreshReg$(_c, "%default%$createUseStyles");
^

ReferenceError: $RefreshReg$ is not defined
    at eval (webpack://react-easy-ssr/./src/assets/jss/components/cssBaselineStyle.ts?:335:1)
    at Object../src/assets/jss/components/cssBaselineStyle.ts (/Users/tomtom94/Code/react-easy-ssr/dist/server/index.js:51:1)
    at __webpack_require__ (/Users/tomtom94/Code/react-easy-ssr/dist/server/index.js:911:41)
    at eval (webpack://react-easy-ssr/./src/components/CssBaseline.tsx?:7:97)
    at Object../src/components/CssBaseline.tsx (/Users/tomtom94/Code/react-easy-ssr/dist/server/index.js:194:1)
    at __webpack_require__ (/Users/tomtom94/Code/react-easy-ssr/dist/server/index.js:911:41)
    at eval (webpack://react-easy-ssr/./src/App.tsx?:21:81)
    at Object../src/App.tsx (/Users/tomtom94/Code/react-easy-ssr/dist/server/index.js:40:1)
    at __webpack_require__ (/Users/tomtom94/Code/react-easy-ssr/dist/server/index.js:911:41)
    at eval (webpack://react-easy-ssr/./src/server/index.tsx?:40:63)

```

If I don't use `react-refresh/babel` plugin for the server, it works good. 

My question is should I use it for server compilation, am I doing right not to include it ? I feel like react-refresh should work on server side also.

**Comment by tomtom94** [comment]
Actually it's normal behavior, no need of HMR on server side

Webpack watches the files on its own an recreates it when necessary

https://github.com/tomtom94/react-easy-ssr/blob/master/scripts/dev.js#L51-L58

```
    serverCompiler.watch(
      {
        ignored: /node_modules/,
        poll: 1000, // Check for changes every second
        aggregateTimeout: 200
      },
      (err, stats) => compilation(err, stats, serverConfig.stats)
    )
```

Thanks a lot.
