### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tapPromise')

### ISSUE THREAD

**Issue by lsbyerley** [pmmmwh/react-refresh-webpack-plugin#740]
After upgrading to `babel-loader` v9, an error is generated from this plugin when running storybook. Has anyone encountered this before?

```
ERR! TypeError: Cannot read properties of undefined (reading 'tapPromise')
ERR!     at /app/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:104:35
ERR!     at Array.forEach (<anonymous>)
ERR!     at ReactRefreshPlugin.apply (/app/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:103:33)
ERR!     at webpack (/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at starterGeneratorFn (/app/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:137:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/app/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:275:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/app/node_modules/@storybook/core-server/dist/cjs/dev-server.js:203:28)
ERR!     at async buildDevStandalone (/app/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
```

```
"babel-loader": "9.1.2",
"@storybook/addon-essentials": "6.5.16",
"@storybook/core": "6.5.16",
"@storybook/react": "6.5.16",
```

**Comment by pmmmwh** [comment]
I believe you might have two versions of `tapable` installed. Can you print your dependency graph or check `node_modules`?

**Comment by lsbyerley** [comment]
upgrading to storybook v7 solved the issue
