### ISSUE TITLE
Incompatible with webpack 4.43.0

### ISSUE THREAD

**Issue by tlaak** [pmmmwh/react-refresh-webpack-plugin#83]
Updating webpack from 4.42.1 to 4.43.0 seems to break the plugin. Downgrading back to 4.42.1 resolves the issue. I can't really understand why it fails the import.

My react-refresh-webpack-plugin version is 0.2.0

```
yarn run v1.22.4
$ NODE_ENV=development webpack-dev-server --env.development
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'webpack'
Require stack:
- /my-project/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/index.js
- /my-project/packages/client/webpack.config.js
- /my-project/packages/client/node_modules/webpack-cli/bin/utils/convert-argv.js
- /my-project/packages/client/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/my-project/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/my-project/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/index.js',
    '/my-project/packages/client/webpack.config.js',
    '/my-project/packages/client/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/my-project/packages/client/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
error Command failed with exit code 1.
```

**Comment by sibelius** [comment]
it is a problem in your node_modules, try to clean up, and install again

**Comment by pmmmwh** [comment]
The error don't seems to be related to the plugin itself - can you try cleaning up `node_modules` and also lock files (`package-lock.json` or `yarn.lock`) and see if the issue resolves itself?

**Comment by tlaak** [comment]
Had to wipe out node_modules and yarn.lock entirely and reinstall to get rid of this error. Possibly a mismatch in webpack types as it got updated when building the lockfile but I don't have it as a direct dependency.
